POST http://localhost:8080/ex_startcode_backend_war_exploded/api/login

{"username":"user2", "password":"test123"}

###
POST http://localhost:8080/ex_startcode_backend_war_exploded/api/info/newuser

{"userName":"user2", "userPass":"test123"}

###
POST http://localhost:8080/ex_startcode_backend_war_exploded/api/game/creategame

{"userName":"user", "userPass":"test123"}

###
GET http://localhost:8080/ex_startcode_backend_war_exploded/api/game/id/1


###
GET http://localhost:8080/ex_startcode_backend_war_exploded/api/characters

###
GET http://localhost:8080/ex_startcode_backend_war_exploded/api/characters/1

###
GET https://miemt.me/werewolf_characters/api/characters