POST http://localhost:8080/ex_startcode_backend_war_exploded/api/login

{"username":"user2", "password":"test123"}

###
POST http://localhost:8080/ex_startcode_backend_war_exploded/api/info/newuser

{"userName":"user2", "userPass":"test123"}

###
POST http://localhost:8080/ex_startcode_backend_war_exploded/api/games/creategame

{"userName":"user", "userPass":"test123"}

###
POST http://localhost:8080/ex_startcode_backend_war_exploded/api/games/1/createplayers

[
{"userName":"user", "userPass":"test123"},
{"userName":"admin", "userPass":"test123"},
{"userName":"user_admin", "userPass":"test123"}
]

###
GET http://localhost:8080/ex_startcode_backend_war_exploded/api/games/1

###
GET http://localhost:8080/ex_startcode_backend_war_exploded/api/games


###
GET http://localhost:8080/ex_startcode_backend_war_exploded/api/characters

###
GET http://localhost:8080/ex_startcode_backend_war_exploded/api/characters/1

###
GET https://miemt.me/werewolf_characters/api/characters

###
PUT http://localhost:8080/ex_startcode_backend_war_exploded/api/games/1/3/vote

{"id":"4", "user":"user_admin","characterId":"0","isAlive":"1","game":"1","latestVote":"3"}

###
PUT http://localhost:8080/ex_startcode_backend_war_exploded/api/games/1/killplayer

{"id":"4", "user":"user_admin","characterId":"0","isAlive":"1","game":"1","latestVote":"3"}

###
PUT http://localhost:8080/ex_startcode_backend_war_exploded/api/games/1/assigncharacters