###
POST http://localhost:8080/ex_startcode_backend_war_exploded/api/info/newuser

{"userName":"BananaWolf", "userPass":"32"}

###
POST http://localhost:8080/ex_startcode_backend_war_exploded/api/login

{"username":"user2", "password":"test123"}

###
GET http://localhost:8080/ex_startcode_backend_war_exploded/api/games

###
POST http://localhost:8080/ex_startcode_backend_war_exploded/api/games/creategame/admin

{"gamepin":"123456"}

###
POST http://localhost:8080/ex_startcode_backend_war_exploded/api/games/3/createplayers

[
{"userName":"user", "userPass":"test123"},
{"userName":"admin", "userPass":"test123"},
{"userName":"user_admin", "userPass":"test123"}
{"userName":"BananaWolf", "userPass":"32"}
]

###
POST http://localhost:8080/ex_startcode_backend_war_exploded/api/games/1/createplayer

{"userName":"admin", "userPass":"test123"}

###
GET http://localhost:8080/ex_startcode_backend_war_exploded/api/games/3

###
GET http://localhost:8080/ex_startcode_backend_war_exploded/api/games

###
GET http://localhost:8080/ex_startcode_backend_war_exploded/api/characters

###
GET http://localhost:8080/ex_startcode_backend_war_exploded/api/characters/1

###
GET https://miemt.me/werewolf_characters/api/characters

###
GET http://localhost:8080/ex_startcode_backend_war_exploded/api/games/1/day

###
PUT http://localhost:8080/ex_startcode_backend_war_exploded/api/games/1/addday

###
PUT http://localhost:8080/ex_startcode_backend_war_exploded/api/games/13/14/vote

{"id":"4", "user":"admin","characterName":"null","isAlive":"1","game":"1","latestVote":"3"}

###
PUT http://localhost:8080/ex_startcode_backend_war_exploded/api/games/7/13/vote

{"id":"14"}

###
GET http://localhost:8080/ex_startcode_backend_war_exploded/api/games/3/voteresult

###
PUT http://localhost:8080/ex_startcode_backend_war_exploded/api/games/1/cleanvotes

###
PUT http://localhost:8080/ex_startcode_backend_war_exploded/api/games/7/rounds/nightroundresult

###
PUT http://localhost:8080/ex_startcode_backend_war_exploded/api/games/3/rounds/dayroundresult

###
GET http://localhost:8080/ex_startcode_backend_war_exploded/api/games/6/rounds/current

###
GET http://localhost:8080/ex_startcode_backend_war_exploded/api/games/1/players

###
GET http://localhost:8080/ex_startcode_backend_war_exploded/api/games/1/getwerewolves

###
PUT http://localhost:8080/ex_startcode_backend_war_exploded/api/games/1/killplayer

{"id":"6"}

###
GET http://localhost:8080/ex_startcode_backend_war_exploded/api/games/7/victims/latest

###
GET http://localhost:8080/ex_startcode_backend_war_exploded/api/games/1/victims

####
GET http://localhost:8080/ex_startcode_backend_war_exploded/api/games/1/aliveplayers

###
PUT http://localhost:8080/ex_startcode_backend_war_exploded/api/games/3/assigncharacters

{"amountOfWerewolves": "2",
"hasHunter": "true"
}

###
GET http://localhost:8080/ex_startcode_backend_war_exploded/api/games/1/rounds

###
GET http://localhost:8080/ex_startcode_backend_war_exploded/api/games/1/rounds/1

###
GET http://localhost:8080/ex_startcode_backend_war_exploded/api/games/1/rounds/0/getnightround

###
GET http://localhost:8080/ex_startcode_backend_war_exploded/api/games/1/rounds/0/getdayround

###
POST http://localhost:8080/ex_startcode_backend_war_exploded/api/games/3/createnightround

###
POST http://localhost:8080/ex_startcode_backend_war_exploded/api/games/3/createdayround

###
GET http://localhost:8080/ex_startcode_backend_war_exploded/api/games/2/hasended

###
GET http://localhost:8080/ex_startcode_backend_war_exploded/api/games/rules